image: python:3.7

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - pip install -r requirements.txt
          - pip install -r requirements-test.txt
          - black --check .
          - isort setup.py bin/pydaikin pydaikin/*.py
          - flake8 .
          - isort bin/pydaikin pydaikin/*.py
          # We are not checking pylint strictly
          - pylint --fail-under=9 bin/pydaikin pydaikin/*.py
